"""Inspector Timeline Engine — operational event spine (Sprint 2 Step 1).

Single source of truth for every lifecycle action of inspection jobs.
Consumers: inspector home rail, admin live feed, future notifications fan-out,
reputation engine, dispute audit, payout reconciliation.

Canonical event shape:
    {
      "id":          "evt_<kind>_<stableKey>",      # stable, dedup key
      "namespace":   "inspector",                   # future: customer/admin/system
      "kind":        "<canonical-kind>",
      "jobId":       "...",                         # required for inspector ops
      "reportId":    "..." | None,
      "vehicleId":   "..." | None,
      "inspectorId": "..." | None,
      "customerId":  "..." | None,
      "actor": {
        "type":   "inspector|admin|customer|qa|system",
        "id":     "<userId or system>",
        "label":  "Human readable label"
      },
      "title":       "Short title",
      "text":        "Human readable summary",
      "severity":    "info|success|warning|critical",
      "timestamp":   "ISO-8601 UTC",
      "metadata":    { ... }                        # arbitrary payload
    }

Idempotency: each canonical event gets a stable id (see `make_event_id`).
append_event uses upsert on `id` — calling it twice is a no-op.

Realtime mirror: every successful append is mirrored to
`app.system.realtime.record_event` (in-memory deque) so admin live feed
keeps working without any change on the transport layer.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Body, Depends, HTTPException, Query
from pydantic import BaseModel

from app.auto_requests.auth import get_user_id_required
from app.core.db import get_db
from app.system.realtime import record_event as record_realtime

router = APIRouter(prefix="/api/inspector", tags=["inspector:timeline"])

# ─────────────────────────────────────────────────────────────────────
# Canonical event kinds
# Each entry: (severity, default_actor_type, default_title)
# `humanReadable` is generated by the caller via `text=...` for richer copy.
# ─────────────────────────────────────────────────────────────────────
CANONICAL_KINDS: Dict[str, tuple] = {
    # Assignment / lifecycle
    "assignment_received":  ("info",     "system",    "Получено новое задание"),
    "assignment_claimed":   ("success",  "inspector", "Задание принято"),
    "assignment_accepted":  ("success",  "inspector", "Задание принято"),       # legacy alias
    "assignment_declined":  ("warning",  "inspector", "Задание отклонено"),
    "provider_departed":    ("info",     "inspector", "Инспектор выехал"),
    "provider_arrived":     ("success",  "inspector", "Инспектор прибыл на место"),
    "inspection_started":   ("info",     "inspector", "Проверка начата"),
    # Media
    "photo_uploaded":       ("info",     "inspector", "Фото добавлено"),        # legacy alias
    "media_uploaded":       ("info",     "inspector", "Медиа загружено"),
    "critical_issue_found": ("critical", "inspector", "Найден критичный дефект"),
    # Contact visibility (Sprint 2 Step 2)
    "contact_masked":       ("info",     "system",    "Контакт частично раскрыт"),
    "contact_revealed":     ("info",     "system",    "Контакт раскрыт"),
    # Intelligence / Draft (Sprint 2 Step 4)
    "draft_generated":      ("info",     "system",    "Черновик сформирован"),
    "draft_flagged":        ("warning",  "system",    "Найдены противоречия в черновике"),
    # Report
    "report_submitted":     ("success",  "inspector", "Отчёт отправлен"),
    "report_approved":      ("success",  "qa",        "Отчёт одобрен QA"),
    "report_rejected":      ("warning",  "qa",        "Отчёт отправлен на доработку"),
    "customer_accepted":    ("success",  "customer",  "Клиент принял проверку"),
    "customer_disputed":    ("critical", "customer",  "Клиент открыл спор"),
    "payout_sent":           ("success", "system",    "Выплата отправлена"),
    # Verification (Sprint 3 Step 1) — admin queue lifecycle
    "verification_submitted": ("info",    "inspector", "Документ отправлен на проверку"),
    "verification_approved":  ("success", "admin",     "Документ подтверждён"),
    "verification_rejected":  ("warning", "admin",     "Документ отклонён"),
    # Reputation (Sprint 3 Step 3) — durable trust layer
    "reputation_promoted":    ("success", "system",    "Рейтинг повышен"),
    "reputation_dropped":     ("warning", "system",    "Рейтинг понижен"),
    "reputation_flagged":     ("warning", "system",    "Hard floor рейтинга активен"),
    # Live Assignments (Sprint 3 Step 4) — dispatch flow
    "assignment_offered":     ("info",    "system",    "Новое предложение"),
    "assignment_accepted":    ("success", "inspector", "Задание принято"),
    "assignment_declined":    ("warning", "inspector", "Задание отклонено"),
    "assignment_expired":     ("warning", "system",    "Предложение истекло"),
    "inspector_assigned":     ("success", "system",    "Инспектор назначен"),
}

SEVERITIES = {"info", "success", "warning", "critical"}
ACTOR_TYPES = {"inspector", "admin", "customer", "qa", "system", "provider"}


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def make_event_id(kind: str, stable_key: str) -> str:
    """Deterministic id used for upsert-based idempotency.

    Map per Step 1 spec:
        assignment_claimed   → evt_claim_<jobId>
        provider_departed    → evt_depart_<jobId>
        provider_arrived     → evt_arrive_<jobId>
        inspection_started   → evt_start_<jobId>
        media_uploaded       → evt_media_<mediaId>
        report_submitted     → evt_submit_<reportId>
        report_approved      → evt_approve_<reportId>
        report_rejected      → evt_reject_<reportId>
        customer_accepted    → evt_customer_accept_<reportId>
    """
    short = {
        "assignment_claimed":  "claim",
        "assignment_accepted": "claim",         # legacy alias collapses to same id
        "provider_departed":   "depart",
        "provider_arrived":    "arrive",
        "inspection_started":  "start",
        "media_uploaded":      "media",
        "photo_uploaded":      "media",         # legacy alias
        "report_submitted":    "submit",
        "report_approved":     "approve",
        "report_rejected":     "reject",
        "customer_accepted":   "customer_accept",
        "customer_disputed":   "customer_dispute",
        "critical_issue_found": "critical",
        "payout_sent":         "payout",
        "assignment_received": "received",
        "assignment_declined": "decline",
    }.get(kind, kind)
    return f"evt_{short}_{stable_key}"


# ─────────────────────────────────────────────────────────────────────
# Index management
# ─────────────────────────────────────────────────────────────────────
_indexes_ready = False


async def ensure_timeline_indexes() -> None:
    """Idempotent index ensure. Called once from lifespan startup."""
    global _indexes_ready
    if _indexes_ready:
        return
    db = get_db()
    try:
        await db.timeline_events.create_index([("inspectorId", 1), ("timestamp", -1)])
        await db.timeline_events.create_index([("jobId", 1), ("timestamp", -1)])
        await db.timeline_events.create_index([("kind", 1), ("timestamp", -1)])
        await db.timeline_events.create_index([("namespace", 1), ("timestamp", -1)])
        await db.timeline_events.create_index([("reportId", 1), ("timestamp", -1)], sparse=True)
        await db.timeline_events.create_index([("vehicleId", 1), ("timestamp", -1)], sparse=True)
        await db.timeline_events.create_index([("customerId", 1), ("timestamp", -1)], sparse=True)
        # Unique index on id for idempotency. Use $exists filter so that legacy
        # documents without `id` (pre-Step 1) don't collide.
        await db.timeline_events.create_index(
            "id", unique=True, partialFilterExpression={"id": {"$exists": True}}
        )
        _indexes_ready = True
    except Exception as e:
        import logging
        logging.getLogger("server").warning(f"timeline indexes ensure failed (non-fatal): {e}")


# ─────────────────────────────────────────────────────────────────────
# Core write
# ─────────────────────────────────────────────────────────────────────
async def append_event(
    *,
    kind: str,
    job_id: Optional[str] = None,
    report_id: Optional[str] = None,
    vehicle_id: Optional[str] = None,
    inspector_id: Optional[str] = None,
    customer_id: Optional[str] = None,
    actor_type: Optional[str] = None,
    actor_id: Optional[str] = None,
    actor_label: Optional[str] = None,
    severity: Optional[str] = None,
    title: Optional[str] = None,
    text: Optional[str] = None,
    metadata: Optional[Dict[str, Any]] = None,
    namespace: str = "inspector",
    stable_key: Optional[str] = None,
    # legacy positional-style kwargs (old callers expect these names)
    payload: Optional[Dict[str, Any]] = None,
    actor: Optional[str] = None,
    human: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    """Idempotent append. Returns the canonical event dict on first write,
    the existing event on retry, or None if persistence failed silently.

    Stability:
      - Never raises to the caller. Failures are logged and swallowed so
        lifecycle endpoints stay green even if Mongo blips.
      - Idempotent via deterministic event `id`. Duplicate appends are
        coalesced.
      - Realtime mirror always runs (best-effort) even when the durable
        write was a no-op duplicate.
    """
    # Resolve defaults from canonical map
    defaults = CANONICAL_KINDS.get(kind, ("info", "system", kind))
    sev_default, actor_default, title_default = defaults

    # Legacy compatibility shims
    if actor is not None and actor_type is None:
        actor_type = actor
    if payload is not None and metadata is None:
        metadata = payload
    if human is not None and text is None:
        text = human

    sev = (severity or sev_default).lower()
    if sev not in SEVERITIES:
        sev = "info"
    a_type = (actor_type or actor_default).lower()
    if a_type not in ACTOR_TYPES:
        a_type = "system"

    # Stable key derivation
    if not stable_key:
        if kind in {"media_uploaded", "photo_uploaded"} and metadata and metadata.get("mediaId"):
            stable_key = str(metadata["mediaId"])
        elif kind in {"report_submitted", "report_approved", "report_rejected",
                      "customer_accepted", "customer_disputed"} and report_id:
            stable_key = str(report_id)
        elif job_id:
            stable_key = str(job_id)
        else:
            # Last-resort: timestamp-based — NOT idempotent but doesn't crash.
            import uuid
            stable_key = uuid.uuid4().hex

    event_id = make_event_id(kind, stable_key)
    now_iso = _now_iso()

    actor_obj = {
        "type": a_type,
        "id": actor_id,
        "label": actor_label or actor_id or a_type,
    }

    event = {
        "id": event_id,
        "namespace": namespace,
        "kind": kind,
        "jobId": job_id,
        "reportId": report_id,
        "vehicleId": vehicle_id,
        "inspectorId": inspector_id,
        "customerId": customer_id,
        "actor": actor_obj,
        "title": title or title_default,
        "text": text or title or title_default,
        "severity": sev,
        "timestamp": now_iso,
        "metadata": metadata or {},
    }

    db = get_db()
    try:
        # Idempotent upsert keyed by stable `id`. If event exists, this is a no-op.
        await db.timeline_events.update_one(
            {"id": event_id},
            {"$setOnInsert": event},
            upsert=True,
        )
    except Exception:
        # Never block calling endpoint
        import logging
        logging.getLogger("server").exception("timeline append failed")
        return None

    # Realtime mirror (always runs — admin live feed never lags behind)
    try:
        record_realtime(f"timeline:{kind}", {k: v for k, v in event.items()})
    except Exception:
        pass

    # Sprint 3 Step 2 — Notification projection. Best-effort; the
    # projector swallows its own errors. If we crash here, the timeline
    # event is still durable (just no user-facing notification).
    try:
        from app.notifications.projector import project_event
        await project_event(event)
    except Exception:
        import logging
        logging.getLogger("server").exception("notification projection failed")

    # Sprint 3 Step 3 — Reputation recompute hook. Same best-effort
    # contract: trigger only on lifecycle kinds (report_*, customer_*,
    # verification_*); reputation_* kinds are excluded inside the hook
    # so we cannot recurse.
    try:
        from app.reputation.engine import recompute_for_event
        await recompute_for_event(event)
    except Exception:
        import logging
        logging.getLogger("server").exception("reputation recompute failed")

    return event


# ─────────────────────────────────────────────────────────────────────
# Public API surface
# ─────────────────────────────────────────────────────────────────────
class AppendBody(BaseModel):
    jobId: Optional[str] = None
    reportId: Optional[str] = None
    kind: str
    severity: Optional[str] = None
    title: Optional[str] = None
    text: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None


@router.post("/timeline/append")
async def append_endpoint(body: AppendBody, uid: str = Depends(get_user_id_required)):
    """Manual append (e.g. inspector flags `critical_issue_found`)."""
    evt = await append_event(
        kind=body.kind,
        job_id=body.jobId,
        report_id=body.reportId,
        inspector_id=uid,
        actor_type="inspector",
        actor_id=uid,
        severity=body.severity,
        title=body.title,
        text=body.text,
        metadata=body.metadata,
    )
    if not evt:
        raise HTTPException(500, "timeline write failed")
    return evt


@router.get("/timeline")
async def list_timeline(
    uid: str = Depends(get_user_id_required),
    jobId: Optional[str] = Query(None),
    reportId: Optional[str] = Query(None),
    kinds: Optional[str] = Query(None, description="Comma-separated kinds"),
    limit: int = Query(100, ge=1, le=500),
):
    """List timeline events for the calling inspector."""
    db = get_db()
    q: Dict[str, Any] = {"inspectorId": uid}
    if jobId:
        q["jobId"] = jobId
    if reportId:
        q["reportId"] = reportId
    if kinds:
        ks = [k.strip() for k in kinds.split(",") if k.strip()]
        if ks:
            q["kind"] = {"$in": ks}

    out: List[Dict[str, Any]] = []
    cursor = db.timeline_events.find(q, {"_id": 0}).sort("timestamp", -1).limit(limit)
    async for r in cursor:
        out.append(r)
    return {"events": out, "count": len(out)}


__all__ = [
    "router",
    "append_event",
    "ensure_timeline_indexes",
    "make_event_id",
    "CANONICAL_KINDS",
]
