"""Customer Inspection Continuity — restrained cognition surface.

V1 doctrine (see review in chat):
  • Customer sees interpretation, not telemetry.
  • Allowlist over event.kind (no schema migration, no visibleTo field).
  • Forbidden lexicon (AI/score/confidence/system/algorithm) is structurally
    impossible — copy is generated by this module only, never proxied from
    operational events.
  • Empty substrate → honest line, no skeletons, no synthetic events.
  • Pure read. No LLM. No polling. Manual refresh only.

Public endpoint:
  GET /api/customer/inspection/{job_id}/continuity
"""
from .router import router

__all__ = ["router"]
