/**
 * auto-request — main StyleSheet (shared by orchestrator + subcomponents).
 *
 * Kept as a single sheet so layout tokens (label spacing, input height,
 * chip padding) stay consistent across the form. Subcomponents import
 * from here instead of re-declaring local styles.
 *
 * The link-preview specific sheet lives in `lpStyles.ts` (separated to
 * keep that visually-rich card self-contained).
 */
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // Geo-1 sprint — country picker modal
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalSheet: { maxHeight: '85%', borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingBottom: 24 },
  modalCloseBtn: { padding: 4 },
  countryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginHorizontal: 16,
    marginVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
  },
  countryRowName: { fontSize: 16, fontWeight: '700' },
  countryRowMeta: { fontSize: 12, marginTop: 2 },
  container: { flex: 1 },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  topTitle: { fontSize: 16, fontWeight: '700', flex: 1, textAlign: 'center' },
  scrollPad: { padding: 18, paddingBottom: 120 },
  h1: { fontSize: 24, fontWeight: '800', letterSpacing: -0.3 },
  h1Sub: { fontSize: 14, marginTop: 8, marginBottom: 24, lineHeight: 20 },
  flowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 16,
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 12,
  },
  flowIconBox: { width: 48, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  flowContent: { flex: 1 },
  flowTitle: { fontSize: 16, fontWeight: '700' },
  flowSub: { fontSize: 13, marginTop: 4, lineHeight: 18 },
  flowMeta: { flexDirection: 'row', marginTop: 8 },
  flowMetaItem: { fontSize: 11, fontWeight: '600' },
  label: { fontSize: 13, fontWeight: '700', marginTop: 18, marginBottom: 8, letterSpacing: 0.2 },
  input: { borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, borderWidth: 1, fontSize: 14 },
  pickerField: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 50,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1.5,
  },
  pickerFieldText: { flex: 1, fontSize: 15, fontWeight: '600' },
  numericInputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 50,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1.5,
  },
  numericInput: { flex: 1, fontSize: 16, fontWeight: '600', paddingVertical: 0 },
  numericPrefix: { fontSize: 15, fontWeight: '700', marginRight: 8 },
  textArea: { minHeight: 84, textAlignVertical: 'top', paddingTop: 12 },
  saveCandidateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1.5,
  },
  saveCandidateTxt: { fontSize: 14, fontWeight: '700', letterSpacing: -0.1 },
  saveCandidateHint: { fontSize: 11, marginTop: 8, textAlign: 'center', lineHeight: 14 },
  hint: { fontSize: 11, marginTop: 4 },
  row2: { flexDirection: 'row', gap: 10 },
  chipsRow: { gap: 8, paddingVertical: 2 },
  chip: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 12, borderWidth: 1, marginRight: 8 },
  chipText: { fontSize: 13, fontWeight: '600' },
  cityField: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 14 },
  cityFieldText: { flex: 1, fontSize: 14 },
  priceNote: { fontSize: 12, textAlign: 'center', marginTop: 12 },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 14,
  },
  errorText: { fontSize: 12, fontWeight: '600', lineHeight: 17 },
  submitBar: { padding: 16, borderTopWidth: 1 },
  submitBtn: { height: 52, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  submitBtnText: { color: '#FFF', fontSize: 15, fontWeight: '700' },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  modalTitle: { fontSize: 16, fontWeight: '700' },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    margin: 14,
    paddingHorizontal: 12,
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
  },
  searchInput: { flex: 1, fontSize: 14 },
  groupTitle: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  cityRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 18, paddingVertical: 14, borderBottomWidth: 1 },
  cityName: { fontSize: 15, fontWeight: '600' },
  cityMeta: { fontSize: 12, marginTop: 2 },
  checkbox: { width: 22, height: 22, borderRadius: 6, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  doneBtn: { margin: 16, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  doneBtnText: { color: '#FFF', fontSize: 15, fontWeight: '700' },
  modalEmpty: { padding: 32, alignItems: 'center' },
  modalEmptyTitle: { fontSize: 16, fontWeight: '700' },
  modalEmptySub: { fontSize: 13, marginTop: 6, textAlign: 'center', lineHeight: 18 },
  suggestBtn: { marginTop: 20, paddingHorizontal: 20, paddingVertical: 12, borderRadius: 12, borderWidth: 1 },
  suggestBtnText: { fontSize: 14, fontWeight: '700' },
  // Value-prop block
  vpBox: { marginTop: 18, padding: 16, borderRadius: 16, borderWidth: 1 },
  vpTitle: { fontSize: 15, fontWeight: '800', marginBottom: 12, letterSpacing: 0.2 },
  vpKicker: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  vpRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 12 },
  vpIconBox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    marginTop: 1,
  },
  vpItemTitle: { fontSize: 14, fontWeight: '700', marginBottom: 2 },
  vpItemSub: { fontSize: 12, lineHeight: 16 },
  vpCheckBox: { marginTop: 4, paddingTop: 14, borderTopWidth: StyleSheet.hairlineWidth },
  vpCheckTitle: { fontSize: 13, fontWeight: '800', marginBottom: 10, letterSpacing: 0.2 },
  vpCheckRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  vpCheckText: { fontSize: 13, lineHeight: 18, fontWeight: '600' },
});
