"""UX-3D — Inspection Report PDF renderer.

Single source of truth: consumes the canonical `_shape_customer_payload`
output. The PDF mirrors the customer-side mobile screen 1-to-1 so that
the same information the customer sees in-app is the artifact shared
with seller / bank / friend.

Structure (per spec):

    Page 1 — Cover
      • Auto title / VIN / year (when known)
      • Inspector signature / report id / completed-at
      • Score + recommendation banner
      • Interpretation headline
      • Top risks (interpretation lines)

    Pages 2+ — Section cards
      • Per-section severity rollup
      • Findings (status • label • status badge)
      • Inspector notes
      • Photo evidence (max 4/item, thumbnail grid)

    Final page
      • Disclaimer
      • Generated by AutoSearch · Report id · Generated-at
"""
from __future__ import annotations

import base64
import io
import logging
from datetime import datetime, timezone
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    BaseDocTemplate, Frame, PageTemplate, Paragraph, Spacer, Table, TableStyle,
    Image as RLImage, PageBreak, KeepTogether,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER

logger = logging.getLogger(__name__)

# Severity → RGB
SEV_COLORS = {
    "critical": colors.HexColor("#dc2626"),
    "warning":  colors.HexColor("#f59e0b"),
    "ok":       colors.HexColor("#16a34a"),
    "na":       colors.HexColor("#9ca3af"),
}
REC_LABELS = {
    "buy":              ("Можно покупать",                "#16a34a"),
    "buy_with_caution": ("Покупать с осторожностью",     "#f59e0b"),
    "avoid":            ("Не рекомендуем покупку",        "#dc2626"),
}
SEV_LABELS = {
    "critical": "Критично",
    "warning":  "Внимание",
    "ok":       "OK",
    "na":       "N/A",
}
SECTION_ICONS = {
    "exterior":    "Кузов",
    "interior":    "Салон",
    "engine":      "Двигатель",
    "suspension":  "Подвеска и тормоза",
    "diagnostics": "Диагностика",
    "test_drive":  "Тест-драйв",
    "documents":   "Документы",
}

# Try to register a Unicode-capable font. ReportLab ships only with Helvetica
# (Latin-1) which breaks Cyrillic. DejaVuSans is installed via fonts-dejavu
# on most Debian images; fall back to Helvetica when absent.
_FONT = "Helvetica"
_FONT_BOLD = "Helvetica-Bold"
try:
    pdfmetrics.registerFont(TTFont("DejaVu", "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"))
    pdfmetrics.registerFont(TTFont("DejaVu-Bold", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"))
    _FONT = "DejaVu"
    _FONT_BOLD = "DejaVu-Bold"
except Exception as exc:  # noqa: BLE001
    logger.warning(f"[pdf] DejaVu font not available, Cyrillic may render as boxes: {exc}")


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()["Normal"]
    return {
        "title":      ParagraphStyle("title",      parent=base, fontName=_FONT_BOLD, fontSize=22, leading=26, textColor=colors.HexColor("#0f172a")),
        "h1":         ParagraphStyle("h1",         parent=base, fontName=_FONT_BOLD, fontSize=16, leading=20, textColor=colors.HexColor("#0f172a")),
        "h2":         ParagraphStyle("h2",         parent=base, fontName=_FONT_BOLD, fontSize=13, leading=17, textColor=colors.HexColor("#0f172a")),
        "body":       ParagraphStyle("body",       parent=base, fontName=_FONT,      fontSize=10, leading=14, textColor=colors.HexColor("#1f2937")),
        "muted":      ParagraphStyle("muted",      parent=base, fontName=_FONT,      fontSize=9,  leading=12, textColor=colors.HexColor("#6b7280")),
        "rec":        ParagraphStyle("rec",        parent=base, fontName=_FONT_BOLD, fontSize=20, leading=24, alignment=TA_CENTER),
        "scoreBig":   ParagraphStyle("scoreBig",   parent=base, fontName=_FONT_BOLD, fontSize=44, leading=50, alignment=TA_CENTER, textColor=colors.HexColor("#0f172a")),
        "scoreHint":  ParagraphStyle("scoreHint",  parent=base, fontName=_FONT,      fontSize=10, leading=12, alignment=TA_CENTER, textColor=colors.HexColor("#6b7280")),
        "interpHead": ParagraphStyle("interpHead", parent=base, fontName=_FONT_BOLD, fontSize=14, leading=18, textColor=colors.HexColor("#0f172a")),
        "interpLine": ParagraphStyle("interpLine", parent=base, fontName=_FONT,      fontSize=11, leading=15, textColor=colors.HexColor("#1f2937")),
        "itemLbl":    ParagraphStyle("itemLbl",    parent=base, fontName=_FONT_BOLD, fontSize=10, leading=13, textColor=colors.HexColor("#0f172a")),
        "itemNote":   ParagraphStyle("itemNote",   parent=base, fontName=_FONT,      fontSize=9,  leading=12, textColor=colors.HexColor("#374151")),
        "badge":      ParagraphStyle("badge",      parent=base, fontName=_FONT_BOLD, fontSize=8,  leading=10, alignment=TA_CENTER, textColor=colors.white),
        "footer":     ParagraphStyle("footer",     parent=base, fontName=_FONT,      fontSize=8,  leading=11, textColor=colors.HexColor("#9ca3af"), alignment=TA_CENTER),
    }


def _format_dt(iso: Any) -> str:
    if not iso:
        return "—"
    try:
        if isinstance(iso, datetime):
            dt = iso
        else:
            dt = datetime.fromisoformat(str(iso).replace("Z", "+00:00"))
        return dt.strftime("%d.%m.%Y · %H:%M")
    except Exception:
        return str(iso)[:16]


def _b64_to_image(b64: str, max_w: float, max_h: float) -> RLImage | None:
    try:
        raw = base64.b64decode(b64)
        buf = io.BytesIO(raw)
        img = RLImage(buf)
        # scale preserving aspect
        iw, ih = img.imageWidth, img.imageHeight
        scale = min(max_w / iw, max_h / ih, 1.0)
        img.drawWidth = iw * scale
        img.drawHeight = ih * scale
        return img
    except Exception as exc:  # noqa: BLE001
        logger.debug(f"[pdf] image decode failed: {exc}")
        return None


def _rec_banner(payload: dict, S: dict) -> Table:
    rec = payload.get("recommendation") or "buy_with_caution"
    label, color_hex = REC_LABELS.get(rec, REC_LABELS["buy_with_caution"])
    score = payload.get("overallScore") or 0.0
    headline = (payload.get("interpretation") or {}).get("headline", "")

    inner = [
        [Paragraph(label, ParagraphStyle("recLbl", parent=S["rec"], textColor=colors.HexColor(color_hex)))],
        [Paragraph(f"{score:.1f}<font size='14' color='#6b7280'> / 10</font>", S["scoreBig"])],
    ]
    if headline:
        inner.append([Paragraph(headline, S["scoreHint"])])

    tbl = Table(inner, colWidths=[170 * mm])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(color_hex + "15")),
        ("BOX",        (0, 0), (-1, -1), 1.2, colors.HexColor(color_hex)),
        ("TOPPADDING", (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("LEFTPADDING",   (0, 0), (-1, -1), 16),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 16),
        ("VALIGN",     (0, 0), (-1, -1), "MIDDLE"),
    ]))
    return tbl


def _interpretation_block(payload: dict, S: dict) -> list:
    interp = payload.get("interpretation") or {}
    lines = interp.get("lines") or []
    if not lines:
        return []
    rows: list[list] = []
    for ln in lines:
        sev = ln.get("severity", "warning")
        color = SEV_COLORS.get(sev, SEV_COLORS["warning"])
        rows.append([
            Paragraph(f"<font color='{color.hexval()}'>●</font>", S["body"]),
            Paragraph(ln.get("title", ""), S["interpLine"]),
        ])
    tbl = Table(rows, colWidths=[8 * mm, 162 * mm])
    tbl.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return [Paragraph("Ключевые наблюдения", S["interpHead"]), Spacer(1, 6), tbl]


def _section_block(s: dict, S: dict, media_lookup: dict[str, dict]) -> list:
    sev = s.get("severity", "ok")
    color = SEV_COLORS.get(sev, SEV_COLORS["ok"])
    title = SECTION_ICONS.get(s["id"], s.get("title", s["id"]))

    # Sub-counters
    parts = []
    if s.get("criticalCount", 0) > 0:
        parts.append(f"<font color='{SEV_COLORS['critical'].hexval()}'>{s['criticalCount']} критич.</font>")
    if s.get("warningCount", 0) > 0:
        parts.append(f"<font color='{SEV_COLORS['warning'].hexval()}'>{s['warningCount']} предупр.</font>")
    if s.get("okCount", 0) > 0:
        parts.append(f"<font color='{SEV_COLORS['ok'].hexval()}'>{s['okCount']} OK</font>")
    sub = "  ·  ".join(parts) or "—"

    header_inner = [[
        Paragraph(f"<b>{title}</b>", ParagraphStyle("secTitle", parent=S["h2"], textColor=colors.HexColor("#0f172a"))),
        Paragraph(sub, S["muted"]),
    ]]
    header_tbl = Table(header_inner, colWidths=[90 * mm, 80 * mm])
    header_tbl.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN",  (1, 0), (1, 0), "RIGHT"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))

    # Sort: critical → warning → ok
    order = {"critical": 0, "warning": 1, "ok": 2, "na": 3}
    items = sorted(s.get("items", []), key=lambda x: order.get(x.get("status", "na"), 9))

    blocks: list = [
        # left-edge color bar via a 1-row table with background
        Table([[header_tbl]], colWidths=[170 * mm], style=TableStyle([
            ("LINEBEFORE", (0, 0), (0, 0), 3, color),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ])),
        Spacer(1, 4),
    ]

    for it in items:
        st = it.get("status", "na")
        st_color = SEV_COLORS.get(st, SEV_COLORS["na"])
        st_lbl = SEV_LABELS.get(st, "—")

        row = [
            Paragraph(f"<font color='{st_color.hexval()}'>●</font>", S["body"]),
            Paragraph(it.get("label", ""), S["itemLbl"]),
            Paragraph(f"<font color='{st_color.hexval()}'><b>{st_lbl}</b></font>", S["muted"]),
        ]
        line_tbl = Table([row], colWidths=[6 * mm, 138 * mm, 26 * mm])
        line_tbl.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("ALIGN",  (2, 0), (2, 0), "RIGHT"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 2),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ]))
        blocks.append(line_tbl)

        if it.get("note"):
            blocks.append(Paragraph(f"<i>{it['note']}</i>", ParagraphStyle("note", parent=S["itemNote"], leftIndent=12)))

        # Photo grid (up to 4 thumbs per item, 36mm each)
        mids = it.get("mediaIds") or []
        if mids:
            imgs: list = []
            for mid in mids[:4]:
                md = media_lookup.get(mid)
                if md and md.get("base64"):
                    rli = _b64_to_image(md["base64"], max_w=36 * mm, max_h=36 * mm)
                    if rli:
                        imgs.append(rli)
            if imgs:
                # pad to even row
                while len(imgs) < 4:
                    imgs.append("")
                grid = Table([imgs], colWidths=[40 * mm] * 4)
                grid.setStyle(TableStyle([
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 2),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 2),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]))
                blocks.append(grid)

        blocks.append(Spacer(1, 4))

    blocks.append(Spacer(1, 8))
    return blocks


def _footer(canvas, doc, S: dict, report_id: str):
    canvas.saveState()
    canvas.setFont(_FONT, 8)
    canvas.setFillColor(colors.HexColor("#9ca3af"))
    gen = datetime.now(timezone.utc).strftime("%d.%m.%Y %H:%M UTC")
    canvas.drawString(20 * mm, 12 * mm, f"AutoSearch · Inspection Report · {report_id}")
    canvas.drawRightString(190 * mm, 12 * mm, f"стр. {doc.page} · сгенерировано {gen}")
    canvas.restoreState()


def render_report_pdf(payload: dict, media_lookup: dict[str, dict] | None = None, vehicle: dict | None = None) -> bytes:
    """Build the inspection PDF from a canonical customer-view payload.

    Args:
        payload: output of `_shape_customer_payload(report)` — single source of truth
        media_lookup: { mediaId → { base64, mime } } — only required when payload has photos
        vehicle: optional { title, vin, year, mileage } for richer cover

    Returns:
        bytes of a complete PDF document.
    """
    media_lookup = media_lookup or {}
    S = _styles()
    out = io.BytesIO()
    report_id = (payload.get("id") or "—")[:8]

    doc = BaseDocTemplate(
        out,
        pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=18 * mm, bottomMargin=20 * mm,
        title=f"AutoSearch Inspection Report {report_id}",
        author="AutoSearch Platform",
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="main")
    doc.addPageTemplates([
        PageTemplate(id="all", frames=[frame], onPage=lambda c, d: _footer(c, d, S, report_id))
    ])

    story: list = []

    # ── Cover ──────────────────────────────────────────────────────────
    story.append(Paragraph("AutoSearch — Отчёт об осмотре", S["title"]))
    story.append(Spacer(1, 4))
    completed = _format_dt(payload.get("completedAt"))
    story.append(Paragraph(f"Завершён: {completed}  ·  Отчёт #{report_id}", S["muted"]))
    story.append(Spacer(1, 16))

    # Vehicle / metadata table
    rows: list[list] = []
    if vehicle:
        if vehicle.get("title"):
            rows.append(["Автомобиль", vehicle["title"]])
        if vehicle.get("vin"):
            rows.append(["VIN", vehicle["vin"]])
        if vehicle.get("year"):
            rows.append(["Год выпуска", str(vehicle["year"])])
        if vehicle.get("mileage"):
            rows.append(["Пробег", f"{vehicle['mileage']:,} км".replace(",", " ")])
    rows.append(["Job ID", str(payload.get("jobId", "—"))[:8]])
    if rows:
        meta = Table(
            [[Paragraph(f"<b>{k}</b>", S["body"]), Paragraph(str(v), S["body"])] for k, v in rows],
            colWidths=[45 * mm, 125 * mm],
        )
        meta.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("LINEBELOW", (0, 0), (-1, -2), 0.3, colors.HexColor("#e5e7eb")),
        ]))
        story.append(meta)
        story.append(Spacer(1, 16))

    story.append(_rec_banner(payload, S))
    story.append(Spacer(1, 14))

    # Interpretation
    interp = _interpretation_block(payload, S)
    if interp:
        story.extend(interp)
        story.append(Spacer(1, 14))

    # Top risks (criticals first 3)
    crits = payload.get("criticalIssues") or []
    if crits:
        story.append(Paragraph("Главные риски", S["interpHead"]))
        story.append(Spacer(1, 4))
        for c in crits[:5]:
            txt = f"• <b>{c.get('label','')}</b>"
            if c.get("note"):
                txt += f" — {c['note']}"
            story.append(Paragraph(txt, ParagraphStyle("risk", parent=S["body"], textColor=SEV_COLORS["critical"])))
        story.append(Spacer(1, 8))

    # ── Section cards ─────────────────────────────────────────────────
    if payload.get("sections"):
        story.append(PageBreak())
        story.append(Paragraph("Подробный отчёт по секциям", S["h1"]))
        story.append(Spacer(1, 8))
        for s in payload["sections"]:
            block = _section_block(s, S, media_lookup)
            # Keep section header + first finding together
            story.append(KeepTogether(block[:2]))
            story.extend(block[2:])

    # ── Disclaimer / final page ──────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph("Юридическая оговорка", S["h2"]))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "Отчёт основан на визуальной и инструментальной проверке, проведённой "
        "инспектором AutoSearch на момент осмотра. Результаты отражают состояние "
        "автомобиля в указанную дату и время и не являются гарантией будущей "
        "исправности. Скрытые дефекты, проявляющиеся только при эксплуатации "
        "или после длительного периода, могут не быть выявлены. AutoSearch не "
        "несёт ответственности за решение о покупке, принятое на основании "
        "данного отчёта.",
        S["body"],
    ))
    story.append(Spacer(1, 14))
    story.append(Paragraph(
        f"Отчёт сгенерирован платформой AutoSearch · ID отчёта {report_id} · "
        f"Job {str(payload.get('jobId','—'))[:8]} · "
        f"Сформирован {datetime.now(timezone.utc).strftime('%d.%m.%Y %H:%M UTC')}",
        S["footer"],
    ))

    doc.build(story)
    out.seek(0)
    return out.read()
